version: "3.9"
services:
    nginx:
        image: "nginx:1.25.3-alpine"
        container_name: "mailerlite-app-nginx"
        restart: always
        links:
            - php-fpm
        volumes:
            - "./mailerlite-app:/var/www/html"
            - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "8080:80"

    php-fpm:
        build: docker/php-fpm
        container_name: "mailerlite-app-fpm"
        restart: always
        links:
            - mysql
        volumes:
            - ./mailerlite-app/:/var/www/html
        environment:
            COMPOSER_ALLOW_SUPERUSER: "1"

    redis:
        image: "redis:7.2.4-alpine"
        container_name: "mailerlite-app-redis"
        environment:
            ALLOW_EMPTY_PASSWORD: "yes"

    mysql:
        image: "mysql:5.6"
        container_name: "mailerlite-app-mysql"
        platform: "linux/x86_64"
        restart: always
        volumes:
            - ".:/var/www/html"
            - "./mysql/data:/var/lib/mysql"
            - "./mysql/logs:/var/log/mysql"
            - "./mysql/conf:/etc/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MARIADB_DATABASE}"
            MYSQL_USER: "${MARIADB_USER}"
            MYSQL_PASSWORD: "${MARIADB_PASSWORD}"

    vite_docker:
        build: docker/node
        container_name: mailerlite-app-vue
        ports:
            - 5173:5173
        volumes:
            - "./mailerlite-vue:/var/www/vue"
        tty: true
        command: /bin/sh -c "yarn && yarn run dev"


